### ISSUE TITLE
Why don't you use services like Heroku to host web-site from this repo?

### ISSUE THREAD

**Issue by Morozov-5F** [tandav/doll-shop#1]
It's totally free and everyone can see, what's that stuff about. I was frustrated a bit -- repository is called "doll-shop", so I eventually thought it was about dolls, but I saw something about TVs in code :)

**Comment by tandav** [comment]
@Morozov-5F Thanks for feedback! 
The reason why I don't host this is that code is shitty as hell. I just learn react & redux technologies in this repo. Actually it should be private repo, but I keep it public 'cause i use github to sync codebase on my laptop and on my work-PC. I don't want to log in to my github account on work-PC, so I just kept repo opened and push to it from both computers.

**Comment by tandav** [comment]
Actually im gonna delete this repo. I don't want anyone see this code.
